<?php

/**
 * @file
 * Module file for Able Player.
 */


use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Defined constants for the default File Entity video and audio bundles.
 */
define('ABLEPLAYER_BUNDLE_AUDIO', 'audio');
define('ABLEPLAYER_BUNDLE_VIDEO', 'video');

/**
 * Defined constants for the supported mimetypes.
 */
define('ABLEPLAYER_MIME_MPEG', 'mpeg');
define('ABLEPLAYER_MIME_OGG', 'ogg');
define('ABLEPLAYER_MIME_MP4', 'mp4');
define('ABLEPLAYER_MIME_WEBM', 'webm');

/**
 * Impelements hook_file_default_types_alter().
 */
function ableplayer_file_default_types_alter(&$types) {
  $types['document']->mimetypes[] = 'text/vtt';
}

/**
 * Implements hook_help().
 */
function ableplayer_help($path, $arg) {
  switch ($path) {

    case 'admin/help#ableplayer':
      $filepath = drupal_get_path('module', 'ableplayer') . '/README.md';

      if (is_file($filepath) && is_readable($filepath)) {
        $readme = file_get_contents($filepath);
      }

      if (!isset($readme)) {
        return NULL;
      }

      if (\Drupal::moduleHandler()->moduleExists('markdown')) {
        $filters = \Drupal::moduleHandler()->invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;

  }
}

/**
 * Implements hook_theme().
 */
function ableplayer_theme(array $existing, $type, $theme, $path) {
  $themes = [];

  $themes['ableplayer_video'] = [
    'variables' => [
      'files' => [],
      'caption' => [],
      'chapter' => [],
      'sign_language' => [],
      'attributes' => NULL,
    ],
  ];

  $themes['ableplayer_audio'] = [
    'variables' => [
      'files' => [],
      'caption' => [],
      'attributes' => NULL,
    ],
  ];

  $themes['ableplayer_caption'] = [
    'variables' => [
      'file' => NULL,
    ],
  ];

  $themes['field__ableplayer_caption'] = [
    'template' => 'field--ableplayer-caption',
    'base hook' => 'field',
  ];

  $themes['ableplayer_chapter'] = [
   'variables' => [
      'file' => NULL,
    ],
  ];

  $themes['field__ableplayer_chapter'] = [
    'template' => 'field--ableplayer-chapter',
    'base hook' => 'field',
  ];

  $themes['ableplayer_sign_language'] = [
    'variables' => [
      'file' => NULL,
    ],
  ];

  $themes['field__ableplayer_sign_language'] = [
    'template' => 'field--ableplayer-sign-language',
    'base hook' => 'field',
  ];

  $themes['ableplayer_poster_image'] = [
    'variables' => [
      'file' => NULL,
    ],
  ];

  $themes['field__ableplayer_poster_image'] = [
    'template' => 'field--ableplayer-poster-image',
    'base hook' => 'field',
  ];

  return $themes;
}
